apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  labels:
    app.kubernetes.io/instance: thanos-af
    app.kubernetes.io/name: grafana-cr
  name: grafana-cr
  namespace: openshift-logging
spec:
  config:
    analytics:
      check_for_updates: false
      reporting_enabled: false
    auth:
      disable_login_form: true
      disable_signout_menu: true
      sigv4_auth_enabled: true
    auth.basic:
      enabled: false
    auth.proxy:
      auto_sign_up: true
      enabled: true
      header_name: X-Forwarded-User
    log:
      level: warn
      mode: console
    security:
      admin_user: 'system:does-not-exist'
      cookie_secure: true
    users:
      auto_assign_org: true
      auto_assign_org_role: Viewer
      default_theme: light
      editors_can_admin: true
      viewers_can_edit: true
  containers:
    - args:
        - '-provider=openshift'
        - '-https-address=:9091'
        - '-http-address='
        - '-email-domain=*'
        - '-upstream=http://localhost:3000'
        - '-openshift-sar={"resource": "namespaces", "verb": "get"}'
        - >-
          -openshift-delegate-urls={"/": {"resource": "namespaces", "verb":
          "get"}}
        - '-tls-cert=/etc/tls/private/tls.crt'
        - '-tls-key=/etc/tls/private/tls.key'
        - >-
          -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
        - '-openshift-service-account=grafana-serviceaccount'
        - '-openshift-ca=/etc/pki/tls/cert.pem'
        - '-openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
        - '-cookie-secret-file=/etc/proxy/secrets/session_secret'
        - '-cookie-expire=24h'
        - '-scope=user:info user:check-access user:list-projects'
        - '-pass-access-token=true'
        - '-pass-basic-auth=false'
        - '-display-htpasswd-form=false'
        - '-htpasswd-file=/etc/proxy/htpasswd/auth'
        - '-skip-provider-button=true'
      image: 'quay.io/openshift/origin-oauth-proxy:4.12'
      name: grafana-proxy
      ports:
        - containerPort: 9091
          name: grafana-proxy
          protocol: TCP
      resources: {}
      volumeMounts:
        - mountPath: /etc/tls/private
          name: secret-grafana-cr-tls
          readOnly: false
        - mountPath: /etc/proxy/secrets
          name: secret-grafana-cr-proxy
          readOnly: false
        - mountPath: /etc/proxy/htpasswd
          name: secret-grafana-cr-htpasswd
          readOnly: true
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
  deployment:
    envFrom:
      - secretRef:
          name: grafana-cr-creds
    skipCreateAdminAccount: true
  ingress:
    enabled: true
    targetPort: grafana-proxy
    termination: reencrypt
  secrets:
    - grafana-cr-tls
    - grafana-cr-proxy
    - grafana-cr-htpasswd
  service:
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: grafana-cr-tls
    ports:
      - name: grafana-proxy
        port: 9091
        protocol: TCP
        targetPort: grafana-proxy
  serviceAccount:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.primary: >-
        {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana-route"}}
