---
kind: GrafanaDataSource
apiVersion: integreatly.org/v1alpha1
metadata:
  namespace: openshift-logging
  name: prometheus
spec:
  name: prometheus
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        timeInterval: 5s
        httpHeaderName1: Authorization
        tlsSkipVerify: true
      name: prometheus
      secureJsonData:
        httpHeaderValue1: 'Bearer ${BEARER_TOKEN}'
      type: prometheus
      url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
---
kind: GrafanaDataSource
apiVersion: integreatly.org/v1alpha1
metadata:
  namespace: openshift-logging
  name: loki
spec:
  name: loki
  datasources:
    - access: proxy
      editable: true
      jsonData:
        tlsSkipVerify: true
      name: Loki (Application)
      secureJsonData: {}
      type: loki
      url: https://logging-loki-gateway-http.openshift-logging.svc.cluster.local:8080/api/logs/v1/application/
    - access: proxy
      editable: true
      jsonData:
        tlsSkipVerify: true
      name: Loki (Infrastructure)
      secureJsonData: {}
      type: loki
      url: https://logging-loki-gateway-http.openshift-logging.svc.cluster.local:8080/api/logs/v1/infrastructure/
